In [2]:
import pandas as pd
import os

/var/folders/l6/ynlhkqws5hv7wtyyn6rr6t4c0000gn/T/ipykernel_10455/3026406390.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

# Overwatch

In [76]:
folder_path = '/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/data/raw/player_csvs/OVERWATCH PLAYERS'

all_files = os.listdir(folder_path)

csv_files = [f for f in all_files if f.endswith('.csv')]

overwatch_players_file_list = []

for csv in csv_files:
    file_path = os.path.join(folder_path, csv)
    try:
        # Try reading the file using default UTF-8 encoding
        df = pd.read_csv(file_path)
        overwatch_players_file_list.append(df)
    except UnicodeDecodeError:
        try:
            # If UTF-8 fails, try reading the file using UTF-16 encoding with tab separator
            df = pd.read_csv(file_path, sep='\t', encoding='utf-16')
            overwatch_players_file_list.append(df)
        except Exception as e:
            print(f"Could not read file {csv} because of error: {e}")
    except Exception as e:
        print(f"Could not read file {csv} because of error: {e}")

In [77]:
overwatch_players_concatenated = pd.concat(overwatch_players_file_list, ignore_index=True)
overwatch_players_concatenated.drop(columns='Unnamed: 0',inplace=True)
overwatch_players_concatenated.drop_duplicates(subset=['name'], inplace=True)

In [78]:
overwatch_players_concatenated['Top 3 Heroes'] = overwatch_players_concatenated['Top 3 Heroes'].astype(str).str.upper()
overwatch_heroes = pd.read_csv('/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/data/raw/specialist_csvs/overwatch_heroes.csv')
overwatch_heroes = list(overwatch_heroes['Hero Name'])
for hero in overwatch_heroes:
    overwatch_players_concatenated[hero]= overwatch_players_concatenated['Top 3 Heroes'].apply(lambda x: hero in x)
overwatch_players_concatenated.drop(columns=['Top 3 Heroes','Cards','Environmental Kills','Multikills','Final Blows','Solo Kills','Objective Time','Hero Damage Done','Objective Kills','Offensive Assists','Defensive Assists','Recon Assists','Melee Final Blows'],inplace=True)
overwatch_players_concatenated = overwatch_players_concatenated.set_index('name').reset_index(level='name')

overwatch_players_concatenated['KDA Ratio'] = overwatch_players_concatenated['KDA Ratio'].apply(lambda x: x.replace(',', '') if isinstance(x, str) and ',' in x else x)
overwatch_players_concatenated['KDA Ratio'] = pd.to_numeric(overwatch_players_concatenated['KDA Ratio'], errors='coerce').astype(float)
overwatch_players_concatenated[overwatch_players_concatenated.select_dtypes(include='object').columns] = overwatch_players_concatenated.select_dtypes(include='object').apply(lambda x: x.str.replace(',', ''))
overwatch_players_concatenated[overwatch_players_concatenated.select_dtypes(include='object').columns] = overwatch_players_concatenated.select_dtypes(include='object').apply(pd.to_numeric, errors='ignore')

/var/folders/l6/ynlhkqws5hv7wtyyn6rr6t4c0000gn/T/ipykernel_10455/628805566.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  overwatch_players_concatenated[overwatch_players_concatenated.select_dtypes(include='object').columns] = overwatch_players_concatenated.select_dtypes(include='object').apply(pd.to_numeric, errors='ignore')

In [79]:
overwatch_players_concatenated

,name,Eliminations,Games Won,Deaths,Assists,KDA Ratio,LÚCIO,WIDOWMAKER,ZENYATTA,ECHO,SOJOURN,MAUGA,MEI,ZARYA,BRIGITTE,HANZO,REAPER,ORISA,ILLARI,LIFEWEAVER,SYMMETRA,KIRIKO,PHARAH,RAMATTRA,D.VA,CASSIDY,ASHE,SIGMA,MERCY,TORBJÖRN,WRECKING BALL,REINHARDT,GENJI,SOMBRA,ROADHOG,MOIRA,TRACER,WINSTON,BAPTISTE,DOOMFIST,SOLDIER: 76,JUNKRAT,BASTION,JUNKER QUEEN,ANA
0,NoobHunter,27577,688,11613,1156,2.37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False
1,Pietjes13,22480,627,8905,12764,2.52,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,TheGoot,13683,609,9073,16303,1.51,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,scorpixSHOW,24261,578,10666,541,2.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
4,Mesjasz,11095,338,5508,7044,2.01,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,h4Percival,1150,72,606,1360,1.90,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
536,LupusRex,9268,394,5594,3685,1.66,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False
537,Rehsile,317,18,298,660,1.06,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
538,akainu,629,26,298,262,2.11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
539,Noah,3336,71,1168,0,2.86,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [81]:
overwatch_players_concatenated.dtypes

name              object
Eliminations       int64
Games Won          int64
Deaths             int64
Assists            int64
KDA Ratio        float64
LÚCIO               bool
WIDOWMAKER          bool
ZENYATTA            bool
ECHO                bool
SOJOURN             bool
MAUGA               bool
MEI                 bool
ZARYA               bool
BRIGITTE            bool
HANZO               bool
REAPER              bool
ORISA               bool
ILLARI              bool
LIFEWEAVER          bool
SYMMETRA            bool
KIRIKO              bool
PHARAH              bool
RAMATTRA            bool
D.VA                bool
CASSIDY             bool
ASHE                bool
SIGMA               bool
MERCY               bool
TORBJÖRN            bool
WRECKING BALL       bool
REINHARDT           bool
GENJI               bool
SOMBRA              bool
ROADHOG             bool
MOIRA               bool
TRACER              bool
WINSTON             bool
BAPTISTE            bool
DOOMFIST            bool
SOLDIER: 76         bool
JUNKRAT             bool
BASTION             bool
JUNKER QUEEN        bool
ANA                 bool
dtype: object

In [82]:
overwatch_players_concatenated.to_csv('overwatch_players_concatenated.csv')

# Apex Legends

In [83]:
folder_path = '/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/data/raw/player_csvs/APEX TOP PLAYERS'

all_files = os.listdir(folder_path)

csv_files = [f for f in all_files if f.endswith('.csv')]

overwatch_players_file_list = []

for csv in csv_files:
    file_path = os.path.join(folder_path, csv)
    try:
        # Try reading the file using default UTF-8 encoding
        df = pd.read_csv(file_path)
        overwatch_players_file_list.append(df)
    except UnicodeDecodeError:
        try:
            # If UTF-8 fails, try reading the file using UTF-16 encoding with tab separator
            df = pd.read_csv(file_path, sep='\t', encoding='utf-16')
            overwatch_players_file_list.append(df)
        except Exception as e:
            print(f"Could not read file {csv} because of error: {e}")
    except Exception as e:
        print(f"Could not read file {csv} because of error: {e}")

In [84]:
apex_players_concatenated = pd.concat(overwatch_players_file_list, ignore_index=True)

In [85]:
columns_to_drop = ['Unnamed: 0', 'Level','Damage','Kills As Kill Leader','Finishers', 'Full Squad Wins',
       'Sniper Kills', 'Season 5 Wins', 'Season 5 Kills', 'Season 6 Wins',
       'Season 6 Kills', 'Season 7 Wins', 'Season 7 Kills', 'Season 11 Wins',
       'Season 11 Kills', 'Season 12 Wins', 'Season 12 Kills','Season 19 Wins',
       'Season 19 Kills', 'Winning Kills','Times Top 3',
       'Pistol Kills', 'Shotgun Kills', 'SMG Kills', 'AR Kills',
       'Care Package Kills', 'Season 10 Kills', 'Season 14 Wins',
       'Season 14 Kills', 'Kills Per Match', 'LMG Kills', 'Season 9 Wins',
       'Season 9 Kills', 'Season 15 Wins', 'Season 15 Kills', 'Season 16 Wins',
       'Season 16 Kills', 'Season 17 Kills', 'Season 8 Kills',
       'Season 10 Wins', 'Season 8 Wins', 'Season 13 Wins', 'Season 13 Kills',
       'Season 17 Wins', 'Season 18 Wins', 'Season 18 Kills', 'Arena Damage',
       'Damage Per Match','Neutral Airdrops Looted',
       'Peak Rank','Arena Wins','Arena Kills','Arena Winstreak']

In [86]:
apex_players_concatenated.drop(columns=columns_to_drop,inplace=True)
column_order = ['name','Kills','Wins','Matches Played','Revives','Headshots','Top 3 Legends']
apex_players_concatenated = apex_players_concatenated[column_order]
apex_players_concatenated['Top 3 Legends'] = apex_players_concatenated['Top 3 Legends'].astype(str).str.upper()

apex_legends = pd.read_csv('/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/data/raw/specialist_csvs/apex_legends.csv')
apex_legends = list(apex_legends['legend_name'])
for legend in apex_legends:
    apex_players_concatenated[legend]= apex_players_concatenated['Top 3 Legends'].apply(lambda x: legend in x)
apex_players_concatenated.drop(columns=['Top 3 Legends'],inplace=True)

In [87]:
apex_players_concatenated

,name,Kills,Wins,Matches Played,Revives,Headshots,BANGALORE,LOBA,LIFELINE,PATHFINDER,BLOODHOUND,HORIZON,MAD MAGGIE,FUSE,RAMPART,WATTSON,BALLISTIC,SEER,CAUSTIC,VANTAGE,CRYPTO,NEWCASTLE,GIBRALTAR,CATALYST,CONDUIT,REVENANT,VALKYRIE,MIRAGE,OCTANE,ASH,WRAITH
0,ghavinci,"51,120","4,259","10,992",NaN,"49,697",False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True
1,Yukinowo,"83,654","4,259","4,979","3,441","70,094",False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
2,Resrect,"120,411","4,258","30,516",20,"133,439",False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
3,vbleedingred,"70,541","4,254","9,439","4,030","48,366",False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
4,her crypt0,"56,409","4,252",NaN,"5,140","87,558",False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,eternusvia,"73,211","2,992","10,594","2,129","18,789",True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
591,BuffWraithPlzTY,"58,850","2,991",781,114,"40,326",False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
592,Zeyquh,"45,447","2,989",NaN,"7,445",NaN,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
593,Stickybudz,"47,286","2,988",NaN,NaN,721,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
594,KIngHedaTTV,"58,287","2,985",NaN,NaN,NaN,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True

In [88]:
apex_players_concatenated.dtypes

name              object
Kills             object
Wins              object
Matches Played    object
Revives           object
Headshots         object
BANGALORE           bool
LOBA                bool
LIFELINE            bool
PATHFINDER          bool
BLOODHOUND          bool
HORIZON             bool
MAD MAGGIE          bool
FUSE                bool
RAMPART             bool
WATTSON             bool
BALLISTIC           bool
SEER                bool
CAUSTIC             bool
VANTAGE             bool
CRYPTO              bool
NEWCASTLE           bool
GIBRALTAR           bool
CATALYST            bool
CONDUIT             bool
REVENANT            bool
VALKYRIE            bool
MIRAGE              bool
OCTANE              bool
ASH                 bool
WRAITH              bool
dtype: object

In [91]:
apex_players_concatenated[apex_players_concatenated.select_dtypes(include='object').columns] = apex_players_concatenated.select_dtypes(include='object').apply(lambda x: x.str.replace(',', ''))
apex_players_concatenated[apex_players_concatenated.select_dtypes(include='object').columns] = apex_players_concatenated.select_dtypes(include='object').apply(pd.to_numeric, errors='ignore')

/var/folders/l6/ynlhkqws5hv7wtyyn6rr6t4c0000gn/T/ipykernel_10455/1975875461.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  apex_players_concatenated[apex_players_concatenated.select_dtypes(include='object').columns] = apex_players_concatenated.select_dtypes(include='object').apply(pd.to_numeric, errors='ignore')

In [97]:
apex_players_concatenated

,name,Kills,Wins,Matches Played,Revives,Headshots,BANGALORE,LOBA,LIFELINE,PATHFINDER,BLOODHOUND,HORIZON,MAD MAGGIE,FUSE,RAMPART,WATTSON,BALLISTIC,SEER,CAUSTIC,VANTAGE,CRYPTO,NEWCASTLE,GIBRALTAR,CATALYST,CONDUIT,REVENANT,VALKYRIE,MIRAGE,OCTANE,ASH,WRAITH
0,ghavinci,51120,4259.0,10992.0,NaN,49697.0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True
1,Yukinowo,83654,4259.0,4979.0,3441.0,70094.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
2,Resrect,120411,4258.0,30516.0,20.0,133439.0,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
3,vbleedingred,70541,4254.0,9439.0,4030.0,48366.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
4,her crypt0,56409,4252.0,NaN,5140.0,87558.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,eternusvia,73211,2992.0,10594.0,2129.0,18789.0,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
591,BuffWraithPlzTY,58850,2991.0,781.0,114.0,40326.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True
592,Zeyquh,45447,2989.0,NaN,7445.0,NaN,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
593,Stickybudz,47286,2988.0,NaN,NaN,721.0,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
594,KIngHedaTTV,58287,2985.0,NaN,NaN,NaN,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True

In [96]:
apex_players_concatenated.to_csv('apex_players_concatenated.csv')

# Rainbow Six

In [125]:
df = pd.read_csv('/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/merged_rainbow.csv')

In [126]:
unique_operators = pd.unique(df[['Top Operator 1', 'Top Operator 2', 'Top Operator 3']].values.ravel('K'))

for operator in unique_operators:
    df[operator] = 0

# Set values based on conditions
for index, row in df.iterrows():
    for operator in unique_operators:
        if row['Top Operator 1'] == operator or row['Top Operator 2'] == operator or row['Top Operator 3'] == operator:
            df.at[index, operator] = 1

df.drop(columns=['Top Operator 1', 'Top Operator 2', 'Top Operator 3','Unnamed: 0'],inplace=True)

In [128]:
df.to_csv('r6_players_concatenated.csv')