In [1]:
import pandas as pd
import os

/var/folders/l6/ynlhkqws5hv7wtyyn6rr6t4c0000gn/T/ipykernel_13786/3026406390.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
folder_path = '/Users/samielzengotita/Documents/IRONHACK/PROYECT/Final-Project/data/cleaned/player_csvs'

all_files = os.listdir(folder_path)

csv_files = [f for f in all_files if f.endswith('.csv')]

overall_players_file_list = []

for csv in csv_files:
    file_path = os.path.join(folder_path, csv)
    try:
        # Try reading the file using default UTF-8 encoding
        df = pd.read_csv(file_path,index_col=0)
        overall_players_file_list.append(df)
    except UnicodeDecodeError:
        try:
            # If UTF-8 fails, try reading the file using UTF-16 encoding with tab separator
            df = pd.read_csv(file_path, sep='\t', encoding='utf-16',index_col=0)
            overall_players_file_list.append(df)
        except Exception as e:
            print(f"Could not read file {csv} because of error: {e}")
    except Exception as e:
        print(f"Could not read file {csv} because of error: {e}")

In [4]:
overwatch_players = overall_players_file_list[0]

In [5]:
rainbow_players = overall_players_file_list[1]

In [6]:
apex_players = overall_players_file_list[2]

In [7]:
bf_players = overall_players_file_list[3]

In [9]:
column_name_mapping = {
    'Eliminations': 'Kills',
    'Games Won': 'Matches_Won',
    'KDA Ratio': 'K/D'
}

overwatch_players.rename(columns=column_name_mapping, inplace=True)

In [10]:
overwatch_players.head()

,name,Kills,Matches_Won,Deaths,Assists,K/D,LÚCIO,WIDOWMAKER,ZENYATTA,ECHO,SOJOURN,MAUGA,MEI,ZARYA,BRIGITTE,HANZO,REAPER,ORISA,ILLARI,LIFEWEAVER,SYMMETRA,KIRIKO,PHARAH,RAMATTRA,D.VA,CASSIDY,ASHE,SIGMA,MERCY,TORBJÖRN,WRECKING BALL,REINHARDT,GENJI,SOMBRA,ROADHOG,MOIRA,TRACER,WINSTON,BAPTISTE,DOOMFIST,SOLDIER: 76,JUNKRAT,BASTION,JUNKER QUEEN,ANA
0,NoobHunter,27577,688,11613,1156,2.37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False
1,Pietjes13,22480,627,8905,12764,2.52,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,TheGoot,13683,609,9073,16303,1.51,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,scorpixSHOW,24261,578,10666,541,2.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
4,Mesjasz,11095,338,5508,7044,2.01,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
column_name_mapping = {
    'MatchesWon': 'Matches_Won',
    'KillAssists': 'Assists',
    'KDRatio': 'K/D'
}
columns_to_drop = ['MatchesLost','HoursPlayed']
rainbow_players.rename(columns=column_name_mapping, inplace=True)
rainbow_players.drop(columns=columns_to_drop,inplace=True)

In [13]:
rainbow_players.head()

,name,K/D,Deaths,Headshots,Matches_Won,WLRatio,Kills,Assists,Revives,TWITCH,ASH,ROOK,BLITZ,JÄGER,THERMITE,SLEDGE,BANDIT,CAVEIRA,LESION,SMOKE,BUCK,VALKYRIE,VIGIL,GSG 9,ELA,MUTE,FROST,DOC,HIBANA,KAPKAN,THATCHER,ACE,PULSE,FINKA,JACKAL,MIRA,SAS,ZOFIA,IQ,GRIDLOCK,BLACKBEARD,MONTAGNE,FUZE,GLAZ,FBI SWAT,CASTLE,ORYX,CLASH,WARDEN,ECHO,NOMAD,KALI,AMARU,TACHANKA,CAPITÃO,MAVERICK,ALIBI,DOKKAEBI,THUNDERBIRD,MOZZIE,IANA,MELUSI,LION,MAESTRO
0,zFanfarrao,2.05,66421,35092,28861,85.3,136175,28643,2145,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,x.C.H.R.I.S.x,1.16,143069,31845,28379,51.3,165987,24511,1566,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,ZootvonKlaus,2.00,68313,39249,27832,75.2,136737,25562,3263,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,x ranl x,1.34,102664,42872,26386,72.2,137081,39054,2374,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,B U T C H E R,1.82,60816,26573,25350,83.7,110821,31855,2143,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
column_name_mapping = {
    'Wins': 'Matches_Won',
}
apex_players['WLRatio'] = (apex_players['Wins'] / (apex_players['Matches Played'] - apex_players['Wins']))*100

apex_players.rename(columns=column_name_mapping, inplace=True)
columns_to_drop = ['Matches Played']
apex_players.drop(columns=columns_to_drop,inplace=True)

In [16]:
apex_players.head()

,name,Kills,Matches_Won,Revives,Headshots,BANGALORE,LOBA,LIFELINE,PATHFINDER,BLOODHOUND,HORIZON,MAD MAGGIE,FUSE,RAMPART,WATTSON,BALLISTIC,SEER,CAUSTIC,VANTAGE,CRYPTO,NEWCASTLE,GIBRALTAR,CATALYST,CONDUIT,REVENANT,VALKYRIE,MIRAGE,OCTANE,ASH,WRAITH,WLRatio
0,ghavinci,51120,4259.0,NaN,49697.0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,63.255607
1,Yukinowo,83654,4259.0,3441.0,70094.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,591.527778
2,Resrect,120411,4258.0,20.0,133439.0,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,16.216010
3,vbleedingred,70541,4254.0,4030.0,48366.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,82.044359
4,her crypt0,56409,4252.0,5140.0,87558.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,NaN

In [18]:
column_name_mapping = {
    'Headshot_Kills': 'Headshots',
    'Win_Ratio': 'WLRatio',
}
columns_to_drop = ['Matches_Lost','Multi_Kills','Melee_Kills']

bf_players.rename(columns=column_name_mapping, inplace=True)
bf_players.drop(columns=columns_to_drop,inplace=True)
bf_players.rename(columns={'Gamer_Tag': 'name'}, inplace=True)

In [19]:
bf_players.head()

,K/D,WLRatio,Kills,Assists,Deaths,Matches_Won,Revives,Headshots,name,Mackay,Zain,Blasco,Lis,Irish,Paik,Falck,Sundance,Crawford,Angel,Boris,Dozer,Casper,Rao
0,1.60,54.9,119835,54654,75055,4565,19476,21561,overpesa,False,False,False,False,False,False,False,False,True,True,True,False,False,False
1,8.92,72.2,328180,184081,36787,4166,6461,14464,TOMBSTONE_ADEM,True,True,False,True,False,False,False,False,False,False,False,False,False,False
2,2.43,61.2,247514,65154,101968,4166,17551,44819,VLKRxAntonAlonso,True,False,False,False,False,False,True,False,False,True,False,False,False,False
3,4.50,42.4,13692,76646,3040,4222,79,8102,Vi-ka75,False,False,False,False,False,False,False,False,False,False,True,False,True,True
4,1.44,53.7,103796,85528,72210,4250,27703,19004,Petrosco,True,False,False,False,False,False,False,False,True,False,True,False,False,False

In [20]:
overwatch_players['Game']='Overwatch'

In [22]:
overwatch_players

,name,Kills,Matches_Won,Deaths,Assists,K/D,LÚCIO,WIDOWMAKER,ZENYATTA,ECHO,SOJOURN,MAUGA,MEI,ZARYA,BRIGITTE,HANZO,REAPER,ORISA,ILLARI,LIFEWEAVER,SYMMETRA,KIRIKO,PHARAH,RAMATTRA,D.VA,CASSIDY,ASHE,SIGMA,MERCY,TORBJÖRN,WRECKING BALL,REINHARDT,GENJI,SOMBRA,ROADHOG,MOIRA,TRACER,WINSTON,BAPTISTE,DOOMFIST,SOLDIER: 76,JUNKRAT,BASTION,JUNKER QUEEN,ANA,Game
0,NoobHunter,27577,688,11613,1156,2.37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,Overwatch
1,Pietjes13,22480,627,8905,12764,2.52,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,Overwatch
2,TheGoot,13683,609,9073,16303,1.51,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,Overwatch
3,scorpixSHOW,24261,578,10666,541,2.27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,Overwatch
4,Mesjasz,11095,338,5508,7044,2.01,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Overwatch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,h4Percival,1150,72,606,1360,1.90,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,Overwatch
536,LupusRex,9268,394,5594,3685,1.66,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,Overwatch
537,Rehsile,317,18,298,660,1.06,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,Overwatch
538,akainu,629,26,298,262,2.11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,Overwatch
539,Noah,3336,71,1168,0,2.86,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,Overwatch

In [23]:
rainbow_players['Game']='Rainbow'

In [24]:
rainbow_players

,name,K/D,Deaths,Headshots,Matches_Won,WLRatio,Kills,Assists,Revives,TWITCH,ASH,ROOK,BLITZ,JÄGER,THERMITE,SLEDGE,BANDIT,CAVEIRA,LESION,SMOKE,BUCK,VALKYRIE,VIGIL,GSG 9,ELA,MUTE,FROST,DOC,HIBANA,KAPKAN,THATCHER,ACE,PULSE,FINKA,JACKAL,MIRA,SAS,ZOFIA,IQ,GRIDLOCK,BLACKBEARD,MONTAGNE,FUZE,GLAZ,FBI SWAT,CASTLE,ORYX,CLASH,WARDEN,ECHO,NOMAD,KALI,AMARU,TACHANKA,CAPITÃO,MAVERICK,ALIBI,DOKKAEBI,THUNDERBIRD,MOZZIE,IANA,MELUSI,LION,MAESTRO,Game
0,zFanfarrao,2.05,66421,35092,28861,85.3,136175,28643,2145,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
1,x.C.H.R.I.S.x,1.16,143069,31845,28379,51.3,165987,24511,1566,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
2,ZootvonKlaus,2.00,68313,39249,27832,75.2,136737,25562,3263,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,Rainbow
3,x ranl x,1.34,102664,42872,26386,72.2,137081,39054,2374,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
4,B U T C H E R,1.82,60816,26573,25350,83.7,110821,31855,2143,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,QKapwn,0.81,110785,18172,12700,49.1,89781,18048,2069,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
532,Voyager.,1.25,48431,15961,12679,70.2,60722,12058,1380,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
533,ES-CON-FIELD,0.81,77338,12252,12673,48.4,62962,21036,2635,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
534,Philias.,1.38,80287,42009,12659,59.6,111124,24583,1716,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow
535,xItsLit,2.25,39687,9652,12655,73.1,89281,5390,584,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Rainbow

In [25]:
apex_players['Game']='Apex'

In [26]:
apex_players

,name,Kills,Matches_Won,Revives,Headshots,BANGALORE,LOBA,LIFELINE,PATHFINDER,BLOODHOUND,HORIZON,MAD MAGGIE,FUSE,RAMPART,WATTSON,BALLISTIC,SEER,CAUSTIC,VANTAGE,CRYPTO,NEWCASTLE,GIBRALTAR,CATALYST,CONDUIT,REVENANT,VALKYRIE,MIRAGE,OCTANE,ASH,WRAITH,WLRatio,Game
0,ghavinci,51120,4259.0,NaN,49697.0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,63.255607,Apex
1,Yukinowo,83654,4259.0,3441.0,70094.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,591.527778,Apex
2,Resrect,120411,4258.0,20.0,133439.0,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,16.216010,Apex
3,vbleedingred,70541,4254.0,4030.0,48366.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,82.044359,Apex
4,her crypt0,56409,4252.0,5140.0,87558.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,NaN,Apex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,eternusvia,73211,2992.0,2129.0,18789.0,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,39.358064,Apex
591,BuffWraithPlzTY,58850,2991.0,114.0,40326.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,-135.339367,Apex
592,Zeyquh,45447,2989.0,7445.0,NaN,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,Apex
593,Stickybudz,47286,2988.0,NaN,721.0,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,NaN,Apex
594,KIngHedaTTV,58287,2985.0,NaN,NaN,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,NaN,Apex

In [27]:
bf_players['Game']='BF2042'

In [28]:
bf_players

,K/D,WLRatio,Kills,Assists,Deaths,Matches_Won,Revives,Headshots,name,Mackay,Zain,Blasco,Lis,Irish,Paik,Falck,Sundance,Crawford,Angel,Boris,Dozer,Casper,Rao,Game
0,1.60,54.9,119835,54654,75055,4565,19476,21561,overpesa,False,False,False,False,False,False,False,False,True,True,True,False,False,False,BF2042
1,8.92,72.2,328180,184081,36787,4166,6461,14464,TOMBSTONE_ADEM,True,True,False,True,False,False,False,False,False,False,False,False,False,False,BF2042
2,2.43,61.2,247514,65154,101968,4166,17551,44819,VLKRxAntonAlonso,True,False,False,False,False,False,True,False,False,True,False,False,False,False,BF2042
3,4.50,42.4,13692,76646,3040,4222,79,8102,Vi-ka75,False,False,False,False,False,False,False,False,False,False,True,False,True,True,BF2042
4,1.44,53.7,103796,85528,72210,4250,27703,19004,Petrosco,True,False,False,False,False,False,False,False,True,False,True,False,False,False,BF2042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,3.48,63.3,244496,79741,70202,4239,29377,39756,MMsuperman0216,True,False,False,False,False,False,True,False,False,True,False,False,False,False,BF2042
215,0.82,47.3,58259,157859,71215,4489,4780,8659,oleg2oleg,False,False,True,True,False,False,False,False,False,False,True,False,False,False,BF2042
216,3.89,76.6,204549,106695,52516,4233,8419,45327,EVH_Tap_God,True,False,False,False,True,False,False,True,False,False,False,False,False,False,BF2042
217,1.77,61.6,79295,27469,44718,4258,15251,15258,Rudeb0yRonin,True,False,False,False,False,False,False,True,False,True,False,False,False,False,BF2042
218,1.76,54.0,207679,73510,117733,4249,33213,28811,OCTOGUE,True,False,False,False,False,False,True,False,False,False,True,False,False,False,BF2042

In [29]:
column_order_df1 = ['name', 'Kills', 'Matches_Won', 'Deaths', 'Assists', 'K/D','Game']
column_order_df2 = ['name', 'Kills', 'Matches_Won', 'Deaths', 'Assists', 'K/D', 'Headshots', 'WLRatio', 'Revives','Game']
column_order_df3 = ['name', 'Kills', 'Matches_Won', 'Headshots', 'WLRatio', 'Revives','Game']
column_order_df4 = ['name', 'Kills', 'Matches_Won', 'Deaths', 'Assists', 'K/D', 'Headshots', 'WLRatio', 'Revives','Game']

# Reorder columns and include remaining columns for each DataFrame
overwatch_players = overwatch_players[column_order_df1 + [col for col in overwatch_players.columns if col not in column_order_df1]]
rainbow_players = rainbow_players[column_order_df2 + [col for col in rainbow_players.columns if col not in column_order_df2]]
apex_players = apex_players[column_order_df3 + [col for col in apex_players.columns if col not in column_order_df3]]
bf_players = bf_players[column_order_df4 + [col for col in bf_players.columns if col not in column_order_df4]]

In [30]:
overwatch_players.head()

,name,Kills,Matches_Won,Deaths,Assists,K/D,Game,LÚCIO,WIDOWMAKER,ZENYATTA,ECHO,SOJOURN,MAUGA,MEI,ZARYA,BRIGITTE,HANZO,REAPER,ORISA,ILLARI,LIFEWEAVER,SYMMETRA,KIRIKO,PHARAH,RAMATTRA,D.VA,CASSIDY,ASHE,SIGMA,MERCY,TORBJÖRN,WRECKING BALL,REINHARDT,GENJI,SOMBRA,ROADHOG,MOIRA,TRACER,WINSTON,BAPTISTE,DOOMFIST,SOLDIER: 76,JUNKRAT,BASTION,JUNKER QUEEN,ANA
0,NoobHunter,27577,688,11613,1156,2.37,Overwatch,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False
1,Pietjes13,22480,627,8905,12764,2.52,Overwatch,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,TheGoot,13683,609,9073,16303,1.51,Overwatch,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,scorpixSHOW,24261,578,10666,541,2.27,Overwatch,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
4,Mesjasz,11095,338,5508,7044,2.01,Overwatch,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
rainbow_players.head()

,name,Kills,Matches_Won,Deaths,Assists,K/D,Headshots,WLRatio,Revives,Game,TWITCH,ASH,ROOK,BLITZ,JÄGER,THERMITE,SLEDGE,BANDIT,CAVEIRA,LESION,SMOKE,BUCK,VALKYRIE,VIGIL,GSG 9,ELA,MUTE,FROST,DOC,HIBANA,KAPKAN,THATCHER,ACE,PULSE,FINKA,JACKAL,MIRA,SAS,ZOFIA,IQ,GRIDLOCK,BLACKBEARD,MONTAGNE,FUZE,GLAZ,FBI SWAT,CASTLE,ORYX,CLASH,WARDEN,ECHO,NOMAD,KALI,AMARU,TACHANKA,CAPITÃO,MAVERICK,ALIBI,DOKKAEBI,THUNDERBIRD,MOZZIE,IANA,MELUSI,LION,MAESTRO
0,zFanfarrao,136175,28861,66421,28643,2.05,35092,85.3,2145,Rainbow,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,x.C.H.R.I.S.x,165987,28379,143069,24511,1.16,31845,51.3,1566,Rainbow,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,ZootvonKlaus,136737,27832,68313,25562,2.00,39249,75.2,3263,Rainbow,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,x ranl x,137081,26386,102664,39054,1.34,42872,72.2,2374,Rainbow,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,B U T C H E R,110821,25350,60816,31855,1.82,26573,83.7,2143,Rainbow,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [32]:
apex_players.head()

,name,Kills,Matches_Won,Headshots,WLRatio,Revives,Game,BANGALORE,LOBA,LIFELINE,PATHFINDER,BLOODHOUND,HORIZON,MAD MAGGIE,FUSE,RAMPART,WATTSON,BALLISTIC,SEER,CAUSTIC,VANTAGE,CRYPTO,NEWCASTLE,GIBRALTAR,CATALYST,CONDUIT,REVENANT,VALKYRIE,MIRAGE,OCTANE,ASH,WRAITH
0,ghavinci,51120,4259.0,49697.0,63.255607,NaN,Apex,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True
1,Yukinowo,83654,4259.0,70094.0,591.527778,3441.0,Apex,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True
2,Resrect,120411,4258.0,133439.0,16.216010,20.0,Apex,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
3,vbleedingred,70541,4254.0,48366.0,82.044359,4030.0,Apex,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
4,her crypt0,56409,4252.0,87558.0,NaN,5140.0,Apex,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True

In [33]:
bf_players.head()

,name,Kills,Matches_Won,Deaths,Assists,K/D,Headshots,WLRatio,Revives,Game,Mackay,Zain,Blasco,Lis,Irish,Paik,Falck,Sundance,Crawford,Angel,Boris,Dozer,Casper,Rao
0,overpesa,119835,4565,75055,54654,1.60,21561,54.9,19476,BF2042,False,False,False,False,False,False,False,False,True,True,True,False,False,False
1,TOMBSTONE_ADEM,328180,4166,36787,184081,8.92,14464,72.2,6461,BF2042,True,True,False,True,False,False,False,False,False,False,False,False,False,False
2,VLKRxAntonAlonso,247514,4166,101968,65154,2.43,44819,61.2,17551,BF2042,True,False,False,False,False,False,True,False,False,True,False,False,False,False
3,Vi-ka75,13692,4222,3040,76646,4.50,8102,42.4,79,BF2042,False,False,False,False,False,False,False,False,False,False,True,False,True,True
4,Petrosco,103796,4250,72210,85528,1.44,19004,53.7,27703,BF2042,True,False,False,False,False,False,False,False,True,False,True,False,False,False

In [34]:
overwatch_players.to_csv('overwatch_players_matched.csv')

In [35]:
rainbow_players.to_csv('rainbow_players_matched.csv')

In [36]:
apex_players.to_csv('apex_players_matched.csv')

In [37]:
bf_players.to_csv('bf_players_matched.csv')